apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  # sample test
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
    hello-1: worldy-1
    hello-2: worldy-2
